### ISSUE TITLE
No message on /gpsfix but can see on /baseline

### ISSUE THREAD

**Issue by devvaibhav455** [swift-nav/swiftnav-ros2#43]
Hi,

I am using swiftnav duro that has 2 receivers (moving base and moving rover) each having its own RJ-45 cable. This goes into a switch and another RJ-45 cable is connected into my Jetson Orin NX that has Jetpack 6.0 (Ubuntu 22.04) with ROS2 Humble.

I installed the driver successfully, can run it, see messages on the `/baseline` topic but nothing on `/gpsfix` or `/navsatfix` 

Here is what I see on the `/baseline` topic
```
---
header:
  stamp:
    sec: 1717183165
    nanosec: 199999999
  frame_id: swiftnav-gnss
mode: 4
satellites_used: 13
baseline_n_m: 2.295
baseline_e_m: -1.568
baseline_d_m: -1.496
baseline_err_h_m: 0.03
baseline_err_v_m: 0.019
baseline_length_m: 3.1565273640505636
baseline_length_h_m: 2.7795051717886765
baseline_orientation_valid: true
baseline_dir_deg: 325.65815748978895
baseline_dir_err_deg: 0.6183858410288549
baseline_dip_deg: -28.29026156110613
baseline_dip_err_deg: 0.3916534734760164
---
```

Below is the ros2 launch log for the driver 

```
nvidia@echo-jetson-orin-nx:~/ros2_ws$ ros2 launch swiftnav_ros2_driver start.py
[INFO] [launch]: All log files can be found below /home/nvidia/.ros/log/2024-05-31-19-26-09-605350-echo-jetson-orin-nx-91545
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [sbp-to-ros-1]: process started with pid [91546]
[sbp-to-ros-1] [INFO] [1717183569.717741941] [rclcpp]: Interface type: 1
[sbp-to-ros-1] [INFO] [1717183569.717897145] [rclcpp]: Connecting to 192.168.131.32:55556
[sbp-to-ros-1] [INFO] [1717183569.718624204] [rclcpp]: Connected
[sbp-to-ros-1] [INFO] [1717183569.718645164] [rclcpp]: Creating 6 publishers
[sbp-to-ros-1] [INFO] [1717183569.718651180] [rclcpp]: Adding publisher gpsfix
[sbp-to-ros-1] [INFO] [1717183569.720300568] [rclcpp]: Adding publisher navsatfix
[sbp-to-ros-1] [INFO] [1717183569.721849825] [rclcpp]: Adding publisher twistwithcovariancestamped
[sbp-to-ros-1] [INFO] [1717183569.722514610] [rclcpp]: Adding publisher baseline
[sbp-to-ros-1] [INFO] [1717183569.723327976] [rclcpp]: Adding publisher timereference
[sbp-to-ros-1] [INFO] [1717183569.723689169] [rclcpp]: Adding publisher imu
[sbp-to-ros-1] [INFO] [1717183569.724304482] [rclcpp]: Logging SBP messages to /home/nvidia/swiftnav/ros2logs/swiftnav-20240531-192609.sbp
[sbp-to-ros-1] [WARN] [1717183577.064835518] [rclcpp]: SBP(WARN): No route to Internet
[sbp-to-ros-1] 
```

Below is the `settings.yaml` file that I use:

```
swiftnav_ros2_driver:
  ros__parameters:

    # SwiftNav GNSS Receiver Interface
    interface: 1 # 1: TCP Client, 2: Serial, 3: File

    # TCP Client (interface: 1)
    #host_ip: "192.168.0.222"
    host_ip: "192.168.131.32"
    host_port: 55556
    read_timeout: 2000  # [ms]
    write_timeout: 2000 # [ms]

    # Serial (interface: 2)
    device_name: "/dev/ttyUSB0"
    connection_str: "115200|N|8|1|N"

    # File (interface: 3)
    sbp_file: "/home/swiftnav/ros2logs/sample-drive.sbp"

    # ROS2 Frame Name
    frame_name: "swiftnav-gnss"

    # Topic Publication Time Stamp Source
    timestamp_source_gnss: True # True: use GNSS receiver reported time (default), False: use current platfrom time

    # RTK Baseline Direction Offsets (Baseline Topic)
    baseline_dir_offset_deg: 0.0    # [deg], range [-180 to 180]
    baseline_dip_offset_deg: 0.0    # [deg], range [-90 to 90]

    # Mininal Speed For Track Updates From SBP Message VEL NED COV (GPSFix Topic)
    track_update_min_speed_mps: 0.2 # [m/s], Track and track error outputs are 'frozen' below this threshold.

    # Publishers
    enabled_publishers:
      [
        "gpsfix",
        "navsatfix",
        "twistwithcovariancestamped",
        "baseline",
        "timereference",
        "imu"
      ]

    # SBP Logging
    log_sbp_messages: True
    log_sbp_filepath: "/home/nvidia/swiftnav/ros2logs"
```

Here is how my network settings look like.

![image](https://github.com/swift-nav/swiftnav-ros2/assets/91839547/36f9d000-1aca-48bf-9a56-8958274cc263)
![image](https://github.com/swift-nav/swiftnav-ros2/assets/91839547/c5cb4661-0c42-4a4a-8f92-3b0c23776da5)

I also tried to check it using a Windows PC using the SwiftNav console (I didn't change the IPv4 settings in windows as suggested in the user manual) and the application was still able to give me the lat long.

Any idea why this might happen?
